- name: Installing postgres and the library for the postgres ansible module
  ansible.builtin.package:
    name:
      - python3-psycopg2
      - postgresql

- name: Create a new database with name "nbxplorer"
  community.postgresql.postgresql_db:
    name: "{{ nbxplorer_db_name }}"
  become: true
  become_user: postgres

- name: Connect to nbxplorer database, create a user
  community.postgresql.postgresql_user:
    login_db: "{{ nbxplorer_db_name }}"
    name: "{{ nbxplorer_db_user }}"
    password: "{{ nbxplorer_db_pass }}"
  become: true
  become_user: postgres

- name: "Grant DB user access its database"
  community.postgresql.postgresql_privs:
    type: database
    login_db: nbxplorer
    roles: nbxplorer
    privs: all
  become: true
  become_user: postgres

- name: "Granting permission to the public schema for our database"
  community.postgresql.postgresql_schema:
    login_db: "nbxplorer"
    name: "public"
    owner: "nbxplorer"
  become: true
  become_user: postgres

- name: Make sure we have the NBXplorer group
  ansible.builtin.group:
    name: '{{ nbxplorer_group }}'

- name: Make sure we have the NBXplorer user
  ansible.builtin.user:
    name: '{{ nbxplorer_user }}'
    group: '{{ nbxplorer_group }}'
  register: nbxplorer_user_info

- name: Ensuring we have a directory with the correct permissions to check out the code
  ansible.builtin.file:
    state: directory
    path: /usr/local/NBXplorer
    owner: '{{ nbxplorer_user }}'
    group: '{{ nbxplorer_group }}'
    mode: "711"
  register: nbxplorer_repo

- name: Checking to see if we already have a checkout of the NBXplorer repo
  ansible.builtin.stat:
    path: /usr/local/NBXplorer/.git
  register: nbxplorer_repo

- name: Making sure we have the latest version of the NBXplorer code
  ansible.builtin.git:
    # clone the repo if it doesn't exist, otherwise update the existing repo
    clone: "{{ not nbxplorer_repo.stat.exists }}"
    dest: "/usr/local/NBXplorer"
    force: true
    refspec: "{{ nbxplorer_git_refspec }}"
    version: "{{ nbxplorer_git_commit }}"
    repo: https://github.com/dgarage/NBXplorer.git
  notify: Building NBXplorer executables
  become: true
  become_user: '{{ nbxplorer_user }}'

- name: Recompile NBXplorer if we got new code
  ansible.builtin.meta: flush_handlers

- name: Building NBXplorer executables
  ansible.builtin.command:
    chdir: "/usr/local/NBXplorer"
    cmd: "./build.sh"
    creates: /usr/local/NBXplorer/NBXplorer/bin/Release/net{{ nbxplorer_dotnet_version }}.0/NBXplorer
  become: true
  become_user: '{{ nbxplorer_user }}'

- name: Writing file with environment variables
  ansible.builtin.template:
    src: templates/env_vars.j2
    dest: /usr/local/NBXplorer/env_vars
    owner: '{{ nbxplorer_user }}'
    group: '{{ nbxplorer_group }}'
    mode: '600'

- name: Setting RPC credentials to authenticate to our bitcoin node
  ansible.builtin.lineinfile:
    regexp: ^[#]btc.rpc.auth=.*
    line: btc.rpc.auth={{ nbxplorer_rpc_username }}:{{ nbxplorer_rpc_password }}
    dest: "{{ nbxplorer_user_info.home }}/.nbxplorer/Main/settings.config"
  notify:
    - Restart nbxplorer

- name: Deploying service to run NBXplorer
  ansible.builtin.template:
    src: templates/nbxplorer.service.j2
    dest: /etc/systemd/system/nbxplorer.service
    mode: '0644'
  notify:
    - Enable and start nbxplorer
